# Generated by Django 6.0.2 on 2026-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fornecedor_produto_fornecedor_delete_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='distribuidora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
