# Generated by Django 6.0.2 on 2026-06-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fornecedor_distribuidora_alter_fornecedor_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
