# Generated by Django 6.0.2 on 2026-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_produto_preco_produto_preco_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
