# Generated by Django 6.0.2 on 2026-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_produto_fornecedor_compra_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('C', 'Cancelada')], default='A', max_length=1),
        ),
    ]
