# Generated by Django 6.0.2 on 2026-06-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_compra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='core.produto'),
        ),
    ]
